import fs from "fs";
import * as Papa from "papaparse";

import Head from "next/head";
import {
  VertContainer,
  Main,
  Title,
  HorContainer,
} from "../components/sharedstyles";
import Options from "../components/options";
import { useEffect, useState } from "react";

enum State {
  Guessing,
  Won,
  Lost,
}

export default function Home({ germanNouns }) {
  const randomIndex = Math.floor(Math.random() * germanNouns.data.length);
  const germanNoun = germanNouns.data[randomIndex];
  const GermanWords = require("german-words");
  const GermanWordsList = require("german-words-dict/dist/words.json");
  console.log(germanNoun);
  const firstAnswer = GermanWords.getGenderGermanWord(
    null,
    GermanWordsList,
    germanNoun[0]
  );
  const [guess, setGuess] = useState("");
  const [noun, setNoun] = useState(germanNoun);
  const [answer, setAnswer] = useState(firstAnswer)
  const [score, setScore] = useState(0);
  const [gameState, setGameState] = useState(State.Guessing);
  const [articleColor, setArticleColor] = useState("Black");
  const [backgroundColor, setBackgroundColor] = useState("Black");

  const handleClick = async (userGuess: string) => {
    setGuess(userGuess);
    const win = userGuess === answer;
    win ? setGameState(State.Won) : setGameState(State.Lost);
    win ? setArticleColor("Green") : setArticleColor("FireBrick");
    win ? setScore((score) => score + 1) : () => {};
    setBackgroundColor("White");
    await new Promise(r => setTimeout(r, 3000));
    setGameState(State.Guessing);
    setBackgroundColor("Black");
    setArticleColor("Black");
    const randomIndex = Math.floor(Math.random() * germanNouns.data.length);
    setNoun(germanNouns.data[randomIndex]);
    setAnswer(GermanWords.getGenderGermanWord(
      null,
      GermanWordsList,
      noun[0]
    ))
    setGuess("");
  };

  const lookup = {
    M: "Der",
    F: "Die",
    N: "Das",
  };

  return (
    <VertContainer>
      <Head>
        <title>LangApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <HorContainer>
          {
            <Title backgroundColor={backgroundColor} color={articleColor}>
              {lookup[answer]}
            </Title>
          }
          <Title backgroundColor="White" color="black">
            {noun[0]}
          </Title>
        </HorContainer>
        <h1>{noun[1]}</h1>
        <Options
          callbackFn={handleClick}
          gameState={gameState}
        />
        <h1>Score: {score}</h1>
      </Main>
    </VertContainer>
  );
}

export async function getServerSideProps() {
  const file = fs.readFileSync("germannouns.csv", "utf-8");
  const germannouns = Papa.parse(file);

  return {
    props: {
      germanNouns: germannouns,
    },
  };
}
